name: React CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm install

      - name: 빌드 실행
        run: npm run build

      - name: EC2에 build 디렉토리 전송 (scp)
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          scp -r -o StrictHostKeyChecking=no -i key.pem ./build ubuntu@${EC2_HOST}:/home/ubuntu/react-app
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: EC2에서 배포 명령 실행 (appleboy ssh)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/react-app
            # 필요한 경우 권한 변경이나 서비스 재시작
