name: React CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm install

      - name: 빌드 실행
        run: npm run build

      - name: EC2에 배포 (scp로 build 디렉토리 전송)
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          scp -r -i key.pem ./build ubuntu@${EC2_HOST}:/home/ubuntu/react-app
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
